// <auto-generated />
using System;
using ECommerce.Data.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ECommerce.Data.Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20221003151156_Product")]
    partial class Product
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Data.Domain.AddressBook.City", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("CountryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PlateCode")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("City", "AddressBook");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6090),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6090),
                            Name = "Adana",
                            PlateCode = "01",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 2L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6097),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6097),
                            Name = "Adıyaman",
                            PlateCode = "02",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 3L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6098),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6098),
                            Name = "Afyon",
                            PlateCode = "03",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 4L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6100),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6099),
                            Name = "Ağrı",
                            PlateCode = "04",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 5L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6101),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6100),
                            Name = "Amasya",
                            PlateCode = "05",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 6L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6105),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6104),
                            Name = "Ankara",
                            PlateCode = "06",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 7L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6106),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6106),
                            Name = "Antalya",
                            PlateCode = "07",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 8L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6107),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6107),
                            Name = "Artvin",
                            PlateCode = "08",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 9L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6108),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6108),
                            Name = "Aydın",
                            PlateCode = "09",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 10L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6110),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6110),
                            Name = "Balıkesir",
                            PlateCode = "10",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 11L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6111),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6111),
                            Name = "Bilecik",
                            PlateCode = "11",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 12L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6113),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6112),
                            Name = "Bingöl",
                            PlateCode = "12",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 13L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6114),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6113),
                            Name = "Bitlis",
                            PlateCode = "13",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 14L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6115),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6114),
                            Name = "Bolu",
                            PlateCode = "14",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 15L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6116),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6115),
                            Name = "Burdur",
                            PlateCode = "15",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 16L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6117),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6117),
                            Name = "Bursa",
                            PlateCode = "16",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 17L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6119),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6118),
                            Name = "Çanakkale",
                            PlateCode = "17",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 18L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6120),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6120),
                            Name = "Çankırı",
                            PlateCode = "18",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 19L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6122),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6122),
                            Name = "Çorum",
                            PlateCode = "19",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 20L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6124),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6123),
                            Name = "Denizli",
                            PlateCode = "20",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 21L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6125),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6124),
                            Name = "Diyarbakır",
                            PlateCode = "21",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 22L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6126),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6126),
                            Name = "Edirne",
                            PlateCode = "22",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 23L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6127),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6127),
                            Name = "Elazığ",
                            PlateCode = "23",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 24L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6128),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6128),
                            Name = "Erzincan",
                            PlateCode = "24",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 25L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6129),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6129),
                            Name = "Erzurum",
                            PlateCode = "25",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 26L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6130),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6130),
                            Name = "Eskişehir",
                            PlateCode = "26",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 27L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6132),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6131),
                            Name = "Gaziantep",
                            PlateCode = "27",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 28L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6134),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6133),
                            Name = "Giresun",
                            PlateCode = "28",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 29L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6135),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6134),
                            Name = "Gümüşhane",
                            PlateCode = "29",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 30L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6136),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6135),
                            Name = "Hakkari",
                            PlateCode = "30",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 31L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6137),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6137),
                            Name = "Hatay",
                            PlateCode = "31",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 32L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6138),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6138),
                            Name = "Isparta",
                            PlateCode = "32",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 33L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6139),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6139),
                            Name = "İçel",
                            PlateCode = "33",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 34L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6141),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6141),
                            Name = "İstanbul",
                            PlateCode = "34",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 35L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6142),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6142),
                            Name = "İzmir",
                            PlateCode = "35",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 36L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6143),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6143),
                            Name = "Kars",
                            PlateCode = "36",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 37L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6144),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6144),
                            Name = "Kastamonu",
                            PlateCode = "37",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 38L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6187),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6186),
                            Name = "Kayseri",
                            PlateCode = "38",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 39L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6188),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6188),
                            Name = "Kırklareli",
                            PlateCode = "39",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 40L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6189),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6189),
                            Name = "Kırşehir",
                            PlateCode = "40",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 41L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6191),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6190),
                            Name = "Kocaeli",
                            PlateCode = "41",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 42L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6192),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6191),
                            Name = "Konya",
                            PlateCode = "42",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 43L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6193),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6192),
                            Name = "Kütahya",
                            PlateCode = "43",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 44L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6194),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6194),
                            Name = "Malatya",
                            PlateCode = "44",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 45L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6195),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6195),
                            Name = "Manisa",
                            PlateCode = "45",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 46L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6196),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6196),
                            Name = "Kahramanmaraş",
                            PlateCode = "46",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 47L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6197),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6197),
                            Name = "Mardin",
                            PlateCode = "47",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 48L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6198),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6198),
                            Name = "Muğla",
                            PlateCode = "48",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 49L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6200),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6200),
                            Name = "Muş",
                            PlateCode = "49",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 50L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6201),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6201),
                            Name = "Nevşehir",
                            PlateCode = "50",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 51L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6203),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6202),
                            Name = "Niğde",
                            PlateCode = "51",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 52L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6204),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6204),
                            Name = "Ordu",
                            PlateCode = "52",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 53L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6205),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6205),
                            Name = "Rize",
                            PlateCode = "53",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 54L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6206),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6206),
                            Name = "Sakarya",
                            PlateCode = "54",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 55L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6207),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6207),
                            Name = "Samsun",
                            PlateCode = "55",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 56L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6208),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6208),
                            Name = "Siirt",
                            PlateCode = "56",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 57L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6209),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6209),
                            Name = "Sinop",
                            PlateCode = "57",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 58L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6210),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6210),
                            Name = "Sivas",
                            PlateCode = "58",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 59L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6211),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6211),
                            Name = "Tekirdağ",
                            PlateCode = "59",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 60L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6212),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6212),
                            Name = "Tokat",
                            PlateCode = "60",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 61L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6214),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6213),
                            Name = "Trabzon",
                            PlateCode = "61",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 62L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6215),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6214),
                            Name = "Tunceli",
                            PlateCode = "62",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 63L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6216),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6215),
                            Name = "Şanlıurfa",
                            PlateCode = "63",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 64L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6217),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6216),
                            Name = "Uşak",
                            PlateCode = "64",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 65L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6218),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6218),
                            Name = "Van",
                            PlateCode = "65",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 66L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6220),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6219),
                            Name = "Yozgat",
                            PlateCode = "66",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 67L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6221),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6220),
                            Name = "Zonguldak",
                            PlateCode = "67",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 68L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6222),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6222),
                            Name = "Aksaray",
                            PlateCode = "68",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 69L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6223),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6223),
                            Name = "Bayburt",
                            PlateCode = "69",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 70L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6224),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6224),
                            Name = "Karaman",
                            PlateCode = "70",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 71L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6225),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6225),
                            Name = "Kırıkkale",
                            PlateCode = "71",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 72L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6226),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6226),
                            Name = "Batman",
                            PlateCode = "72",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 73L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6227),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6227),
                            Name = "Şırnak",
                            PlateCode = "73",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 74L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6228),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6228),
                            Name = "Bartın",
                            PlateCode = "74",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 75L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6229),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6229),
                            Name = "Ardahan",
                            PlateCode = "75",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 76L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6230),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6230),
                            Name = "Iğdır",
                            PlateCode = "76",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 77L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6231),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6231),
                            Name = "Yalova",
                            PlateCode = "77",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 78L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6233),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6232),
                            Name = "Karabük",
                            PlateCode = "78",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 79L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6234),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6233),
                            Name = "Kilis",
                            PlateCode = "79",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 80L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6235),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6234),
                            Name = "Osmaniye",
                            PlateCode = "80",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 81L,
                            CountryID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6236),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6235),
                            Name = "Düzce",
                            PlateCode = "81",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        });
                });

            modelBuilder.Entity("ECommerce.Data.Domain.AddressBook.Country", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("CodeISO")
                        .HasColumnType("text");

                    b.Property<string>("CodeISO3")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PhoneCode")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Country", "AddressBook");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CodeISO = "TR",
                            CodeISO3 = "TUR",
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(5967),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(5955),
                            Name = "Türkite",
                            PhoneCode = "90",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        });
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Catalog.Category", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Category", "Catalog");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Catalog.Category_i18n", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("LanguageID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Category_i18n", "Catalog");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Catalog.Product", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product", "Catalog");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Catalog.Product_i18n", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("LanguageID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("ProductID");

                    b.ToTable("Product_i18n", "Catalog");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Configuration.Language", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("CultureCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IconName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IsoCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Language", "Configuration");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CultureCode = "tr",
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(7241),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(7240),
                            IsoCode = "tr",
                            Name = "Türkçe",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 2L,
                            CultureCode = "en",
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(7246),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(7246),
                            IsoCode = "en",
                            Name = "English",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        });
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Configuration.Parameter", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Module")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Parameter", "Configuration");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Logging.AuditLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryKey")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("AuditLog", "Logging");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Logging.ExceptionLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FunctionName")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<string>("MachineName")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("SessionID")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("ExceptionLog", "Logging");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Membership.Permission", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Permission", "Membership");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Membership.Role", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Role", "Membership");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6422),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6421),
                            Name = "Admin",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 2L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6427),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(6426),
                            Name = "User",
                            StatusID = (byte)1,
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        });
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Membership.RolePermission", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("PermissionID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PermissionID");

                    b.HasIndex("RoleID");

                    b.ToTable("RolePermission", "Membership");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Membership.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsGlobalAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<long?>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<byte>("StatusID")
                        .HasColumnType("smallint");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<long>("UserCreatedID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserModifiedID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("User", "Membership");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(7193),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(7192),
                            EmailAddress = "admin@admin.com",
                            FullName = "Admin Admin",
                            IsGlobalAdmin = true,
                            Name = "Admin",
                            PasswordHash = new byte[] { 145, 49, 123, 243, 98, 71, 81, 127, 215, 99, 106, 225, 74, 152, 123, 243, 93, 98, 103, 56, 151, 145, 118, 191, 26, 109, 61, 170, 85, 162, 136, 60, 215, 66, 203, 29, 9, 248, 178, 208, 89, 130, 101, 75, 91, 75, 62, 207, 246, 11, 164, 33, 53, 50, 232, 246, 58, 49, 85, 52, 10, 119, 116, 53 },
                            PasswordSalt = new byte[] { 254, 200, 25, 135, 87, 49, 11, 32, 212, 29, 141, 164, 219, 94, 18, 53, 124, 141, 28, 10, 57, 223, 222, 230, 118, 12, 0, 84, 250, 44, 5, 8, 130, 134, 115, 218, 70, 216, 239, 12, 194, 110, 176, 126, 187, 221, 156, 123, 175, 105, 102, 207, 113, 147, 229, 247, 242, 74, 192, 50, 179, 124, 56, 225, 157, 126, 45, 105, 27, 49, 187, 222, 79, 120, 150, 144, 207, 73, 113, 85, 220, 246, 131, 78, 61, 88, 93, 83, 31, 253, 105, 45, 183, 119, 68, 157, 120, 69, 135, 130, 246, 39, 179, 86, 234, 220, 34, 99, 229, 71, 26, 71, 13, 144, 241, 82, 3, 181, 34, 166, 30, 146, 235, 15, 24, 200, 208, 247 },
                            RoleID = 1L,
                            StatusID = (byte)1,
                            Surname = "Admin",
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        },
                        new
                        {
                            ID = 2L,
                            DateCreated = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(7202),
                            DateModified = new DateTime(2022, 10, 3, 18, 11, 55, 603, DateTimeKind.Local).AddTicks(7201),
                            EmailAddress = "user@user.com",
                            FullName = "User User",
                            IsGlobalAdmin = false,
                            Name = "User",
                            PasswordHash = new byte[] { 145, 49, 123, 243, 98, 71, 81, 127, 215, 99, 106, 225, 74, 152, 123, 243, 93, 98, 103, 56, 151, 145, 118, 191, 26, 109, 61, 170, 85, 162, 136, 60, 215, 66, 203, 29, 9, 248, 178, 208, 89, 130, 101, 75, 91, 75, 62, 207, 246, 11, 164, 33, 53, 50, 232, 246, 58, 49, 85, 52, 10, 119, 116, 53 },
                            PasswordSalt = new byte[] { 254, 200, 25, 135, 87, 49, 11, 32, 212, 29, 141, 164, 219, 94, 18, 53, 124, 141, 28, 10, 57, 223, 222, 230, 118, 12, 0, 84, 250, 44, 5, 8, 130, 134, 115, 218, 70, 216, 239, 12, 194, 110, 176, 126, 187, 221, 156, 123, 175, 105, 102, 207, 113, 147, 229, 247, 242, 74, 192, 50, 179, 124, 56, 225, 157, 126, 45, 105, 27, 49, 187, 222, 79, 120, 150, 144, 207, 73, 113, 85, 220, 246, 131, 78, 61, 88, 93, 83, 31, 253, 105, 45, 183, 119, 68, 157, 120, 69, 135, 130, 246, 39, 179, 86, 234, 220, 34, 99, 229, 71, 26, 71, 13, 144, 241, 82, 3, 181, 34, 166, 30, 146, 235, 15, 24, 200, 208, 247 },
                            RoleID = 2L,
                            StatusID = (byte)1,
                            Surname = "User",
                            UserCreatedID = 0L,
                            UserModifiedID = 0L
                        });
                });

            modelBuilder.Entity("ECommerce.Data.Domain.AddressBook.City", b =>
                {
                    b.HasOne("ECommerce.Data.Domain.AddressBook.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Catalog.Category_i18n", b =>
                {
                    b.HasOne("ECommerce.Data.Domain.Catalog.Category", "Category")
                        .WithMany("Category_i18n")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Domain.Configuration.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Catalog.Product", b =>
                {
                    b.HasOne("ECommerce.Data.Domain.Catalog.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Catalog.Product_i18n", b =>
                {
                    b.HasOne("ECommerce.Data.Domain.Configuration.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Membership.RolePermission", b =>
                {
                    b.HasOne("ECommerce.Data.Domain.Membership.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Data.Domain.Membership.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Membership.User", b =>
                {
                    b.HasOne("ECommerce.Data.Domain.Membership.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.AddressBook.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Catalog.Category", b =>
                {
                    b.Navigation("Category_i18n");
                });

            modelBuilder.Entity("ECommerce.Data.Domain.Membership.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
